# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR
# ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

PYEXEC=python

FILE1=rforest_pfracs.py
FILE2=predict_P.py
FILE3=table2raster.py
FILE4=var_importances.py
FILE5=di.py
FILE6=plots.py


pmaps: $(FILE1) $(FILE2) $(FILE3) $(FILE4) $(FILE5) $(FILE6)

	$(PYEXEC) $(FILE1) occ_p
	$(PYEXEC) $(FILE1) mineral_p
	$(PYEXEC) $(FILE1) inorg_p
	$(PYEXEC) $(FILE1) org_p
	$(PYEXEC) $(FILE1) avail_p
	$(PYEXEC) $(FILE1) total_p

	$(PYEXEC) $(FILE2)
	$(PYEXEC) $(FILE3)
	$(PYEXEC) $(FILE4)
	$(PYEXEC) $(FILE5)
	$(PYEXEC) $(FILE6)
